dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'

dotenv: .env

networks:
  development:
    verify: False
  kovan:
    verify: True
  ropsten:
    verify: True
  bsc-test:
    verify: True
  mainnet-fork-dev:
    verify: False
  mainnet:
    verify: True